/* Generated by hooks/regen-tracker-dashboard.sh. Do not edit. */
window.SIGNALS = {
  "generated_at": "2026-08-24T11:18:59+00:00",
  "lessons": {
    "weekly": [
      {
        "week_start": "2026-08-03",
        "count": 0
      },
      {
        "week_start": "2026-08-10",
        "count": 0
      },
      {
        "week_start": "2026-08-17",
        "count": 0
      },
      {
        "week_start": "2026-08-24",
        "count": 0
      }
    ],
    "undated_total": 1
  }
};
